[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
batch_size = 1  # Deploy one contract at a time to avoid nonce issues
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./" },  # Allow creating directories
    { access = "read", path = "./script" },
    { access = "read", path = "./src" }
]


[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
